---
editor: 
  markdown: 
    wrap: 72
---

# Introduction

Following a recent viewing of Sharknado (2013), concerns from management
have been raised regarding the hypothetical yet sensational scenario in
which coastal tornadoes that form over marine life habitats might carry
any animals, but particularly sharks, inland. While the narrative of the
film relies heavily on science fiction and overly dramatic exaggeration,
the underlying anxiety reflects a far more serious question: How might
increasingly volatile weather patterns, driven by the effects of climate
change, affect storm behavior in coastal regions?

This question is especially pressing as global warming and other climate
concerns continue to influence the frequency, distribution, and
intensity of severe weather events. Studies, including recent research
done by Woods et al. (2023) [@Woods_2023], suggest that climate change
is already contributing to heightened atmospheric instability. These
shifts are only expected to intesify the energy dynamics that fuel
storms such as tornadoes and hurricanes, potentially leading to more
powerful and erratic weather events. For populations residing near
coastlines, the risk of damage from such events - regardless of any
involvement of deposited sharks - is a growing concern.

This report aims to assess the scientific plausibility of tornadoes
forming in shark-populated coastal zones and transporting said objects
inland. While the idea of airborne sharks remains highly improbable, the
broader premise of increasingly intense tornadoes with heightened
capacity for inland travel warrants legitimate analysis. Drawing on data
from the National Oceanic and Atmospheric Administration (NOAA), as well
as the National Marine Fisheries Service (NMFS), this investigation
evaluates the proximity of tornado tracks to known shark stations and
examines the physical criteria that would be required for such
transportation to occur.

Ultimately, the objective of this analysis is not to validate a
fictional scenario, but rather to use it as a lens through which to
explore emerging risks linked to climate patterns. The findings provide
a novel perspective on extreme storm dynamics and are intended to inform
future emergency preparedness and risk mitigation strategies.
